name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.23'

      # Run Go tests in the src folder
      - name: Go Test
        run: |
          cd src
          go test ./... -v
